clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: composer-artifacts

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - COMPOSERVER=--2
      - DOCUMENT_ROOT=/test/composer-artifacts

pipeline:
  composer-install-lowest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
    - /cache:/cache
    commands:
    - composer update --prefer-lowest --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
    - /cache:/cache
    commands:
    - composer self-update --2
    - composer install --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
    - ./vendor/bin/grumphp run

  phpunit-lowest:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
    - ./vendor/bin/phpunit
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  phpunit-highest:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

matrix:
  PHP_VERSION:
    - 7.4
    - 8.0
  COMPOSER_BOUNDARY:
    - lowest
    - highest
