workspace:
  base: /test
  path: composer-artifacts

services:
  web:
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    environment:
     - DOCUMENT_ROOT=/test/composer-artifacts

pipeline:

  composer-install:
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    volumes:
      - /cache:/cache
    commands:
      - composer install

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    commands:
      - ./vendor/bin/phpunit

matrix:
  IMAGE_PHP:
    - fpfis/php56-build:latest
    - fpfis/php71-build:latest