workspace:
  base: /test
  path: composer-artifacts

services:
  web:
    image: fpfis/php56-build:latest
    environment:
     - DOCUMENT_ROOT=/test/composer-artifacts

pipeline:

  composer-install:
    image: fpfis/php56-build:latest
    volumes:
      - /cache:/cache
    commands:
      - composer install

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit
